# Defaults for all languages
baseurl: "/"
publishDir: "temp/hugo"
MetaDataFormat: "yaml"
blackfriday:
  hrefTargetBlank: true
title: "MarzeeLab's Besugo"
googleAnalytics: ""
taxonomies:
  tag: "tags"

# i18n
DefaultContentLanguage: "en"
DefaultContentLanguageInSubdir: true

# Params per language
Languages:
  en:
    locale: "en-GB"
    description: "MarzeeLab's boilerplate for the Hugo static site generator, coupled with NetlifyCMS driving Github as a backend."
  pt:
    locale: "pt-PT"
    description: "Boilerplate da MarzeeLabs para o gerador de sites estáticos Hugo, integrando o NetlifyCMS para uso da plataform GitHub como backend."
