backend:
  name: github
  repo: marzeelabs/besugo # Path to your Github repository
  branch: develop # Branch to update (master by default)

media_folder: "/static/images/uploads" # Folder where user uploaded files should go
public_folder: "/images/uploads"

collections: # A list of collections the CMS should be able to edit
  - name: "blog_post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Blog Post" # Used in the UI, ie.: "New Post"
    folder: "content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - label: "Post title"
        name: "title"
        widget: "string"
      - label: "Post Cover"
        name: "image"
        widget: "image"
      - label: "Content"
        name: "body"
        widget: "markdown"
